[package]
name = "btc_anchoring_sandbox"
version = "0.1.0"
authors = ["Ivan Ivashchenko <ivan.ivashchenko@xdev.re",
           "Aleksey Sidorov <aleksei.sidorov@xdev.re>"]

[dependencies]
btc_anchoring_service = {version="0.1", path="../", features=["sandbox_tests"]}

bitcoinrpc = {version="0.1", path="../3rdparty/bitcoinrpc"}
bitcoin="0.9.0"
secp256k1 = "0.6.0"
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"
byteorder = "1.0.0"
log = "0.3.0"
rand = "0.3.0"
libc = "0.2.21"
router = "0.5.1"
iron = "0.5.1"
iron-test = "0.5.0"

[dependencies.exonum]
version = "0.1.0"
git = "ssh://git@github.com/exonum/exonum-core.git"
rev = "5e1547a8a76e42409fe86852d26515b12dc3b0f5"

[dependencies.sandbox]
version = "0.1.0"
git = "ssh://git@github.com/exonum/exonum-core.git"
rev = "5e1547a8a76e42409fe86852d26515b12dc3b0f5"
