language: rust
rust:
  - stable
cache: cargo
sudo: required
dist: trusty
env:
  global:
  - ANCHORING_RELAY_HOST=http://127.0.0.1:18332
  - ANCHORING_USER=travis
  - ANCHORING_PASSWORD=travis
  - RUST_LOG=off
  - NIGHTLY_RUST=nightly-2017-01-08
  - CLIPPY_VERS=0.0.107
  - RUSTFMT_VERS=0.8.4
  
before_install:
- rustfmt -V | grep $RUSTFMT_VERS || cargo install rustfmt --vers $RUSTFMT_VERS --force
- rustup override set $NIGHTLY_RUST
- cargo +$NIGHTLY_RUST clippy -V | grep $CLIPPY_VERS || cargo +$NIGHTLY_RUST install clippy --vers $CLIPPY_VERS --force
- rustc --version
- cargo --version
- sudo add-apt-repository -y ppa:chris-lea/libsodium
- sudo apt-add-repository -y ppa:bitcoin/bitcoin
- sudo apt-get -qq update
install:
- sudo apt-get -qq --yes install gcc g++ make libsodium-dev libleveldb-dev libssl-dev
- sudo apt-get -qq --yes install bitcoind
before_script:
- bitcoind -regtest -server -rpcuser=travis -rpcpassword=travis -daemon
- sleep 10
- bitcoin-cli -regtest -rpcuser=travis -rpcpassword=travis generate 200
script:
- cargo fmt -- --write-mode=diff
- cargo fmt -p anchoring_btc_sandbox -- --write-mode=diff
- cargo clippy -- -D warnings
- cargo test --release
- cargo test --manifest-path sandbox_tests/Cargo.toml
after_script:
- bitcoin-cli -regtest -rpcuser=travis -rpcpassword=travis stop
notifications:
  slack:
    rooms:
      secure: jR9W2Gz4RPs5RCswXU/+MH2UpDzXFfvBTZ6YAdDO+g+xIV9BRVQoAHcM5eDi3+WBUXww/yQYldEN26kUH/TjnRnk48ThTBjfTyf3Iu/g4z9WTX7YorFsDzuDk03kIZ+g0hgZnugmVC2QwOB7hyacHCLtEsNhkYsQ6FVpf5yzFLIsQNtKwhkza/gPmFUmqxSht6S4Qe6oYLOU08LppQQd0U2vzP03mHEd8zXD08F3+06t58sE0AvFJGHRP6SukNXXopfEQ4rsx1TtzNrSSn0QU/BPLzofl5lmJ8dajtDSh12/f4ag4Fvf+/RLrQrcPb1+yW9G7Ip+OuhuaRSoBBvbkwtE3B2jHknReM4uA0PMLat5RrN0MmtgRjLCavEj9ORIkd1JJ1RmbC26DIJWd+kaLhZ6+C3vfK5A/aIQa9Shn2xD5bjOcsSpPmgiJ10HeoWDc9YLfaXQd3ezOk+Ye9nWhMnbgIlUX8qq89o9IN0Ikdj/62yTbBBmIovLhjxleu/EbKDlcDW/9I3+b5H766+/8RorBXztARuJ8BeBUfWeENgEC+8poQXG1b2TEIurmYOGSfZEsY1WjdU2PZ/f3TyU/eE55rvnPyWyINV/TtSKDyl5bfNbEM28BbbDjzYY7450JcTvuvlKpqCYG9M3Te3Hrb3nbQJfeXbtMeQv307gm1k=
