[package]
name = "exonum-btc-anchoring"
version = "0.4.0"
authors = ["The Exonum Team <exonum@bitfury.com>"]
homepage = "https://exonum.com/doc/advanced/bitcoin-anchoring/"
repository = "https://github.com/exonum/exonum-btc-anchoring"
documentation = "https://docs.rs/exonum-btc-anchoring"
readme = "README.md"
license = "Apache-2.0"
keywords = ["exonum", "blockchain", "bitcoin", "anchoring"]
categories = ["database-implementations"]
description = "An Exonum service that provides anchoring to Bitcoin blockchain."

[badges]
travis-ci = { repository = "exonum/exonum-btc-anchoring" }

[dependencies]
exonum = "0.4.0"
exonum_bitcoinrpc = "0.3.0"

bitcoin="0.10.0"
secp256k1 = "0.6.0"
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"
byteorder = "1.0.0"
log = "0.4.0"
clap = "2.22.1"
rand = "0.3.0"
derive-error = "0.0.4"
router = "0.6.0"
iron = "0.6.0"
mount = "0.4.0"
toml = "0.4.0"
tempdir = "0.3.5"

[dev-dependencies]
exonum-testkit = "0.1.0"
exonum-configuration = "0.4.0"
libc = "0.2.21"
pretty_assertions = "0.4.0"

[features]
default = []
rpc_tests = []

[patch.crates-io]
exonum = { git = 'https://github.com/exonum/exonum', rev = '627d1cf' }
exonum-testkit = { git = 'https://github.com/exonum/exonum-testkit', rev = '73cb369' }
exonum-configuration = { git = 'https://github.com/exonum/exonum-configuration', rev = 'a8551bc' }
