[package]
name = "exonum-btc-anchoring"
edition = "2018"
version = "0.12.0"
authors = ["The Exonum Team <exonum@bitfury.com>"]
homepage = "https://exonum.com/doc/advanced/bitcoin-anchoring/"
repository = "https://github.com/exonum/exonum-btc-anchoring"
documentation = "https://docs.rs/exonum-btc-anchoring"
readme = "README.md"
license = "Apache-2.0"
keywords = ["exonum", "blockchain", "bitcoin", "anchoring"]
categories = ["database-implementations"]
description = "An Exonum service that provides anchoring to Bitcoin blockchain."

[badges]
travis-ci = { repository = "exonum/exonum-btc-anchoring" }

[dependencies]
bitcoin = { version = "0.18", features = ["serde"] }
bitcoin_hashes = { version = "0.3", features = ["serde"] }
bitcoincore-rpc = "0.7.0"
btc-transaction-utils = "0.6"
byteorder = "1.3"
derive_more = "0.15"
exonum = "0.12.0"
exonum-cli = { git = "https://github.com/exonum/exonum.git", rev = "00998fa2b1d4f47d37d5154bb3a863b28249f014" }
exonum-crypto = { features = ["with-protobuf"], git = "https://github.com/exonum/exonum.git", rev = "00998fa2b1d4f47d37d5154bb3a863b28249f014" }
exonum-derive = "0.12.0"
exonum-merkledb = "0.12.0"
exonum-proto = { git = "https://github.com/exonum/exonum.git", rev = "00998fa2b1d4f47d37d5154bb3a863b28249f014" }
exonum-supervisor = { git = "https://github.com/exonum/exonum.git", rev = "00998fa2b1d4f47d37d5154bb3a863b28249f014" }
exonum-testkit = "0.12.0"
failure = "0.1"
failure_derive = "0.1"
futures = "0.1"
hex = "0.4"
jsonrpc = "0.11"
log = "0.4"
protobuf = { version = "2.8", features = ["with-serde"] }
rand = "0.4"
reqwest = "0.9"
secp256k1 = { version = "0.12", features = ["serde"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_str = "0.1"
structopt = "0.3"

[dev-dependencies]
proptest = "0.9"

[build-dependencies]
exonum-build = "0.12.0"

[patch.crates-io]
exonum = { git = "https://github.com/exonum/exonum.git", rev = "00998fa2b1d4f47d37d5154bb3a863b28249f014" }
exonum-build = { git = "https://github.com/exonum/exonum.git", rev = "00998fa2b1d4f47d37d5154bb3a863b28249f014" }
exonum-derive = { git = "https://github.com/exonum/exonum.git", rev = "00998fa2b1d4f47d37d5154bb3a863b28249f014" }
exonum-merkledb = { git = "https://github.com/exonum/exonum.git", rev = "00998fa2b1d4f47d37d5154bb3a863b28249f014" }
exonum-testkit = { git = "https://github.com/exonum/exonum.git", rev = "00998fa2b1d4f47d37d5154bb3a863b28249f014" }
