[package]
name = "btc_anchoring_service"
version = "0.1.0"
authors = ["Ivan Ivashchenko <ivan.ivashchenko@xdev.re",
           "Aleksey Sidorov <aleksei.sidorov@xdev.re>"]
readme	= "README.md"

[workspace]
members = ["sandbox_tests"]

[dependencies]
bitcoinrpc = {version="0.1", path="3rdparty/bitcoinrpc"}
bitcoin="0.9.0"
secp256k1 = "0.6.0"
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"
byteorder = "1.0.0"
log = "0.3.0"
clap = "2.22.1"
tempdir = "0.3.0"
rand = "0.3.0"
derive-error = "0.0.3"
router = "0.5.1"
iron = "0.5.1"
bodyparser = "0.5.0"
params = "0.6.0"
mount = "0.3.0"

[dependencies.exonum]
version = "0.1.0"
git = "ssh://git@github.com/exonum/exonum-core.git"
rev = "f8a283d376173ee9fb81e7d0ff306b78be0f0729"

[dependencies.configuration_service]
version = "0.1.0"
git = "ssh://git@github.com/exonum/exonum-configuration.git"
rev = "10ee86946064f7a55ae79cc6248e69952435b716"

[features]
default = []
sandbox_tests = []
