[package]
name = "exonum-btc-anchoring"
edition = "2018"
version = "0.12.0"
authors = ["The Exonum Team <exonum@bitfury.com>"]
homepage = "https://exonum.com/doc/advanced/bitcoin-anchoring/"
repository = "https://github.com/exonum/exonum-btc-anchoring"
documentation = "https://docs.rs/exonum-btc-anchoring"
readme = "README.md"
license = "Apache-2.0"
keywords = ["exonum", "blockchain", "bitcoin", "anchoring"]
categories = ["database-implementations"]
description = "An Exonum service that provides anchoring to Bitcoin blockchain."

[badges]
travis-ci = { repository = "exonum/exonum-btc-anchoring" }

[dependencies]
bitcoin = { version = "0.17", features = ["serde"] }
bitcoin_hashes = { version = "0.3", features = ["serde"] }
btc-transaction-utils = "0.5"
byteorder = "1.3"
derive_more = "0.15"
exonum = "0.12.0"
exonum-merkledb = "0.12.0"
exonum_bitcoinrpc = "0.6"
exonum-derive = "0.12.0"
exonum-testkit = "0.12.0"
failure = "0.1"
failure_derive = "0.1"
hex = "0.3"
log = "0.4"
maplit = "1.0"
matches = "0.1"
protobuf = { version = "2.8", features = ["with-serde"] }
rand = "0.4"
secp256k1 = { version = "0.12", features = ["serde"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_str = "0.1"
structopt = "0.3"
toml = "0.5"

[dev-dependencies]
libc = "0.2"
proptest = "0.9"

[build-dependencies]
exonum-build = "0.12.0"

[patch.crates-io]
exonum = { git = "https://github.com/alekseysidorov/exonum.git", rev = "5b50333e618b20aa05d81464e2bd25a55ee629ba" }
exonum-merkledb = { git = "https://github.com/alekseysidorov/exonum.git", rev = "5b50333e618b20aa05d81464e2bd25a55ee629ba" }
exonum-derive = { git = "https://github.com/alekseysidorov/exonum.git", rev = "5b50333e618b20aa05d81464e2bd25a55ee629ba" }
exonum-testkit = { git = "https://github.com/alekseysidorov/exonum.git", rev = "5b50333e618b20aa05d81464e2bd25a55ee629ba" }
exonum-build = { git = "https://github.com/alekseysidorov/exonum.git", rev = "5b50333e618b20aa05d81464e2bd25a55ee629ba" }

