[package]
name = "btc_anchoring_service"
version = "0.1.0"
authors = ["Exonum Team <exonum@bitfury.com>"]
readme	= "README.md"

[workspace]
members = ["sandbox_tests"]

[dependencies]
bitcoinrpc = {version="0.1", path="3rdparty/bitcoinrpc"}
bitcoin="0.9.0"
secp256k1 = "0.6.0"
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"
byteorder = "1.0.0"
log = "0.3.0"
clap = "2.22.1"
tempdir = "0.3.0"
rand = "0.3.0"
derive-error = "0.0.3"
router = "0.5.1"
iron = "0.5.1"
bodyparser = "0.5.0"
params = "0.6.0"
mount = "0.3.0"

[dependencies.exonum]
version = "0.1.0"
git = "ssh://git@github.com/exonum/exonum.git"
rev = "cf87780b3de1ba161c490e0700870a0f2c308136"

[dependencies.configuration_service]
version = "0.1.0"
git = "ssh://git@github.com/exonum/exonum-configuration.git"
rev = "f4e6f405c8127e35b0b56422573f1ebb78a5ce43"

[features]
default = []
sandbox_tests = []
