[package]
name = "exonum-btc-anchoring"
version = "0.9.0"
authors = ["The Exonum Team <exonum@bitfury.com>"]
homepage = "https://exonum.com/doc/advanced/bitcoin-anchoring/"
repository = "https://github.com/exonum/exonum-btc-anchoring"
documentation = "https://docs.rs/exonum-btc-anchoring"
readme = "README.md"
license = "Apache-2.0"
keywords = ["exonum", "blockchain", "bitcoin", "anchoring"]
categories = ["database-implementations"]
description = "An Exonum service that provides anchoring to Bitcoin blockchain."

[badges]
travis-ci = { repository = "exonum/exonum-btc-anchoring" }

[dependencies]
bitcoin = { version = "0.14", features = ["serde"] }
btc-transaction-utils = "0.3"
byteorder = "1.2"
clap = "2.32"
derive_more = "0.11"
display_derive = "0.0"
exonum = "0.9.1"
exonum_bitcoinrpc = "0.5.1"
exonum-testkit = "0.9.1"
failure = "0.1"
failure_derive = "0.1"
log = "0.4"
maplit = "1.0"
matches = "0.1"
rand = "0.4"
secp256k1 = { version = "0.11", features = ["serde"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_str = "0.1"
tempdir = "0.3"
toml = "0.4"

[dev-dependencies]
exonum-configuration = "0.9.1"
libc = "0.2"
pretty_assertions = "0.5"
proptest = "0.8"

[features]
default = []
testnet_tests = []
